# build does not work on Java 9 or later as Java 5 is not a valid target

name: Build

on: [push]

permissions:
  contents: read

jobs:
  build:
    permissions:
      security-events: write  # for github/codeql-action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/joda-time/joda-time/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
    - run: touch starting_build_Checkout_26
    - run: rm starting_build_Checkout_26
    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  #v3.0.2

    - run: touch starting_build_SetupJDK_29
    - run: rm starting_build_SetupJDK_29
    - name: Set up JDK
      uses: actions/setup-java@2c7a4878f5d120bd643426d54ae1209b29cc01a3  #v3.4.1
      with:
        java-version: 8
        distribution: 'temurin'
        cache: 'maven'

    - run: touch starting_build_Mavenversion_36
    - run: rm starting_build_Mavenversion_36
    - name: Maven version
      run: |
        mkdir -p ./.mvn
        echo '-e -B -DtrimStackTrace=false' > ./.mvn/maven.config
        mvn --version
        mkdir -p target

    - run: touch starting_build_InitializeCodeQL_43
    - run: rm starting_build_InitializeCodeQL_43
    - name: Initialize CodeQL
      uses: github/codeql-action/init@8aff97f12c99086bdb92ff62ae06dbbcdf07941b  #codeql-bundle-20221105
      with:
        languages: java
    
    - run: touch starting_build_Mavenbuild_48
    - run: rm starting_build_Mavenbuild_48
    - name: Maven build
      run: |
        mvn install site

    - run: touch starting_build_PerformCodeQLAnalysis_52
    - run: rm starting_build_PerformCodeQLAnalysis_52
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@8aff97f12c99086bdb92ff62ae06dbbcdf07941b  #codeql-bundle-20221105
    
    - run: touch starting_build_Website_55
    - run: rm starting_build_Website_55
    - name: Website
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN_GH }}
      run: |
        chmod +x ./.github/website.sh
        .github/website.sh
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: Execute py script # run file
      if: always()
      run: |
        python .github/workflows/script.py
    - run: cp /home/runner/inotify-logs.csv /home/runner/work/joda-time/joda-time/optimizing-ci-builds-ci-analysis/
      if: always()
    - name: Pushes analysis to another repository
      if: always()
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'optimizing-ci-builds-ci-analysis'
        destination-github-username: 'Priya-it'
        destination-repository-name: 'ci-analyzes'
        target-branch: 'joda-time.1671744188'
        target-directory: 'joda-time/1671744188/.github/workflows/build/build'

